### ISSUE TITLE
Dear Mr.K

### ISSUE THREAD

**Issue by BrenchCC** [StitchK/StitchK.github.io#7]
God K, why are you so awesome!

**Comment by StitchK** [comment]
Fking God B,u are fking handsome bro ,let me suck

**Comment by StitchK** [comment]
不是，波哥，怎么发送信息啊github

**Comment by BrenchCC** [comment]
> 不是，波哥，怎么发送信息啊github

额只能用issue提问题发额

**Comment by StitchK** [comment]
啊额那你怎么发过来的啊波哥

**Comment by BrenchCC** [comment]
就你去别人项目那里，提一个issue问题，然后绑定了邮箱，有人回复有通知额

**Comment by StitchK** [comment]
啊额这样吗ok啊波哥
爱你哦
